#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/usr/bin/udp2raw

validate_section_udp2raw() {
	uci_load_validate udp2raw udp2raw "$1" "$2" \
		'enabled:bool:0'
}

udp2raw_instance() {
	local section="$1"
	local enabled alias server_addr server_port local_addr local_port
	local raw_mode key cipher_mode auth_mode auto_rule keep_rule seq_mode
	local other_args

	config_get_bool enabled "$section" "enabled" "0"
	[ "$enabled" = "0" ] && return 1

	config_get alias "$section" "alias"
	config_get server_addr "$section" "server_addr"
	config_get server_port "$section" "server_port"
	config_get local_addr "$section" "local_addr" "0.0.0.0"
	config_get local_port "$section" "local_port"
	config_get raw_mode "$section" "raw_mode" "faketcp"
	config_get key "$section" "key"
	config_get cipher_mode "$section" "cipher_mode" "aes128cbc"
	config_get auth_mode "$section" "auth_mode" "md5"
	config_get_bool auto_rule "$section" "auto_rule" "1"
	config_get_bool keep_rule "$section" "keep_rule" "0"
	config_get seq_mode "$section" "seq_mode" "1"
	config_list_foreach "$section" "other_args" append_arg

	[ -z "$server_addr" -o -z "$server_port" -o -z "$local_port" ] && return 1

	procd_open_instance
	procd_set_param command $PROG
	procd_append_param command -s -l "${local_addr}:${local_port}" -r "${server_addr}:${server_port}"
	procd_append_param command --raw-mode "$raw_mode"
	[ -n "$key" ] && procd_append_param command -k "$key"
	procd_append_param command --cipher-mode "$cipher_mode"
	procd_append_param command --auth-mode "$auth_mode"
	[ "$auto_rule" = "1" ] && procd_append_param command -a
	[ "$keep_rule" = "1" ] && procd_append_param command --keep-rule
	procd_append_param command --seq-mode "$seq_mode"
	[ -n "$other_args" ] && procd_append_param command $other_args
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

append_arg() {
	local cfg="$1"
	other_args="$other_args $cfg"
}

start_service() {
	config_load udp2raw
	config_foreach udp2raw_instance servers
	config_foreach udp2raw_instance clients
}

service_triggers() {
	procd_add_reload_trigger "udp2raw"
	procd_add_validation validate_section_udp2raw
}

reload_service() {
	stop
	start
}